### ISSUE TITLE
발사된 탄알의 실체는 총구 위치에서 정상적으로 발사될 수 없다

### ISSUE THREAD

**Issue by XiongGaPuo** [We-Cant-Coding/TACZ-Fabric#1]
![{C4C9B205-15B7-4a3e-8569-99F55E807E65}](https://github.com/user-attachments/assets/35befe62-8158-41a1-8675-e32e0a7d0ea9)

**Comment by XiongGaPuo** [comment]
![image](https://github.com/user-attachments/assets/b91a2875-faad-43e1-a70f-b14f09c85474)

**Comment by XiongGaPuo** [comment]
Tacz의 fabric 버전을 만들어 주셔서 정말 감사합니다. 이 디스플레이 버그가 처리되기를 바랍니다

**Comment by LaeDev** [comment]
I'm glad to hear that someone has already built and tried it, and I've already fixed what you're talking about and it will be in the next commit.

我很高兴听到有人已经构建并尝试了它，而且我已经修正了你所说的问题，这将在下一次提交中出现。
