### ISSUE TITLE
Not compatible with Resolution Control

### ISSUE THREAD

**Issue by XiaoQiAWA** [We-Cant-Coding/TACZ-Fabric#10]
[ ] Please Report Your Bug in English. Other Language Will be Likely Ignored.
[ ] If the bug is also in forge, it will be likely won't be fixed.

**Describe the bug**
Not compatible with [https://modrinth.com/mod/resolution-control-plus](url)Resolution Control
There is no such bug when loading Resolution Control with Sinytra Connector on Forge
**Minecraft Infomation :**
https://mclo.gs/hKWwU3L

**Comment by LaeDev** [comment]
Fixed. Will be applyed in 1.0.3 or hotfix version.
