### ISSUE TITLE
The new version is not compatible with Iris

### ISSUE THREAD

**Issue by XiaoQiAWA** [We-Cant-Coding/TACZ-Fabric#12]
[ ] Please Report Your Bug in English. Other Language Will be Likely Ignored.
[ ] If the bug is also in forge, it will be likely won't be fixed.

**Describe the bug**
In the new version (1.0.2-hotfix2) it is not compatible with Iris (1.7.2), it is reduced to 1.0.2 version for compatibility

**To Reproduce**
1. Take out a gun that supports the scope
2. Take out any of the scopes
3. Equip the gun that supports the scope
**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/66d4ac72-deb2-48f3-8571-25f5e0fa9358)

**Minecraft Infomation :**
Logs of the time when the bug [https://mclo.gs/UGpVRqf](https://mclo.gs/UGpVRqf)

**Comment by LaeDev** [comment]
Duped Problem With Discord. Already Fixed And will be Applied at hotfix-3
