### ISSUE TITLE
Controller support

### ISSUE THREAD

**Issue by cnopt** [We-Cant-Coding/TACZ-Fabric#13]
Any chance you could add support for controllers? It's my preferred way of playing and I would love to use this mod

I can see in the input classes it's requiring a mouse input to be used, any chance that can be removed so it can be bound to a controller? I'm not sure how to build from source to test for myself, but seems crazy that it just flat out needs a mouse for some reason

**Comment by LaeDev** [comment]
We already have that feature in 1.0.3 (which is beta version. patreon only for now.) the release of 1.0.3 is prob end of this month or not.
