### ISSUE TITLE
The scope causes a drastic drop in the game's frame rate.

### ISSUE THREAD

**Issue by smallmoss233** [We-Cant-Coding/TACZ-Fabric#16]
When I equipped the scope, my game's frame rate suddenly dropped from 108 to 30 frames per second, and it could not break through 30 frames unless I restarted the game.

Game Version: 1.20.1
Mod Loader: Fabric 0.16.3, Mod Version: 1.0.2

**Comment by LaeDev** [comment]
Use latest hotfix version. If it is, send the modlist.

**Comment by LaeDev** [comment]
**Whether it will be fixed or not is unknown.**

**Comment by qualk** [comment]
@smallmoss233 Did the latest version fix the issue?

**Comment by smallmoss233** [comment]
> 最新版本是否解决了问题？
No, but my screen went black before the frame drops, and my game is loaded with immersive portals and adapted sodium, which may be caused by this, but I need both mods

**Comment by LaeDev** [comment]
> > 最新版本是否解决了问题？
> > No, but my screen went black before the frame drops, and my game is loaded with immersive portals and adapted sodium, which may be caused by this, but I need both mods

i've seen immersive portals are causing this issue. even crash. but i'm not planning to support in immersive portals as rn.
