### ISSUE TITLE
[Bug]: Mixin conflict with Apugli

### ISSUE THREAD

**Issue by qualk** [We-Cant-Coding/TACZ-Fabric#19]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

Minecraft 1.20.1 - Fabric Loader 0.15.11

### tac version

1.0.2-hotfix3

### Related Mods

```raw
Apugli
TaCZ
```

### Description

https://github.com/MCModderAnchor/TACZ/issues/241

> I went to use TaCZ alongside some other mods in a modpack for a server, and the client crashed when it was used alongside Apugli. Looking into the console it seemed to be a sort of mixin error.

### Step to reproduce

Install TaCZ 1.0.2 for Fabric.
Install Apugli 2.10.4
Game doesn't start, it exits with code -1

### Logs & Crash reports

https://mclo.gs/jrSqxin

**Comment by qualk** [comment]
Mixin conflict: https://github.com/MerchantPug/apugli/blob/1.20.4/common/src/main/java/net/merchantpug/apugli/mixin/xplatform/client/HeldItemRendererMixin.java and https://github.com/We-Cant-Coding/TACZ-Fabric/blob/1.20.1/src/main/java/com/tacz/guns/mixin/client/HeldItemRendererMixin.java

Specific error:
```
@Redirect conflict. Skipping tacz.mixins.json:client.HeldItemRendererMixin from mod tacz->@Redirect::renderFirstPersonItemMainHand(Lnet/minecraft/class_759;Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V with priority 1000, already redirected by apugli.mixins.json:client.HeldItemRendererMixin from mod apugli->@Redirect::apugli$renderModifiedItemFirstPersonMainhand(Lnet/minecraft/class_759;Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V with priority 1000
@Redirect conflict. Skipping tacz.mixins.json:client.HeldItemRendererMixin from mod tacz->@Redirect::renderFirstPersonItemMainHand(Lnet/minecraft/class_759;Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V with priority 1000, already redirected by apugli.mixins.json:client.HeldItemRendererMixin from mod apugli->@Redirect::apugli$renderModifiedItemFirstPersonOffhand(Lnet/minecraft/class_759;Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V with priority 1000

org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector renderFirstPersonItemMainHand(Lnet/minecraft/class_759;Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V in tacz.mixins.json:client.HeldItemRendererMixin from mod tacz failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tacz-fabric-1.20.1-refmap.json
```

**Comment by KrokusAstra** [comment]
I have the same issue, i guess i wouldn't enable tacz for a while in launcher, until this bug fixed

**Comment by qualk** [comment]
Issue opened in the Agpuli repo @ https://github.com/MerchantPug/apugli/issues/83

**Comment by LaeDev** [comment]
Apugli causes a lot of bugs due to mixin confilct, and i'm not dealing with another confilct issue as rn.
