### ISSUE TITLE
Zoomify dont work, it just dont do the zoom

### ISSUE THREAD

**Issue by RalsFemboy** [We-Cant-Coding/TACZ-Fabric#2]
With TACZ Fabric you cant use zoomify as a zoom mod, it just dont work

To Reproduce
1. Install Zoomify
2. Remove TACZ c bind
3. Press C

**Comment by RalsFemboy** [comment]
Also I made my onw build like few hours after you guys make the realse

**Comment by LaeDev** [comment]
We'll try to fix it as soon as we can, but the builds in the discord are based on older commits, so you can stay up to date by checking out the releases on GitHub.

**Comment by RalsFemboy** [comment]
it was not a discord build, it was my own build i make it like a day ago

**Comment by LaeDev** [comment]
> it was not a discord build, it was my own build i make it like a day ago

I already know that, I just wanted to let you know that you don't have to build it yourself 😃

**Comment by RalsFemboy** [comment]
ok i going to try with the realse of the mod, if it fix the problem

**Comment by RalsFemboy** [comment]
Nop it just dont work, f6 also dont work just make the f1 thing but no zoom

**Comment by LaeDev** [comment]
Thanks, is it just the Zoomify mode that doesn't zoom?

**Comment by RalsFemboy** [comment]
Yes C and F6 Not does the zoom part

**Comment by LaeDev** [comment]
> Yes C and F6 Not does the zoom part

![image](https://github.com/user-attachments/assets/94ac74b6-4314-4f75-8b42-d50051afecc8)
fixed. will be applyed in next commit and release.
