### ISSUE TITLE
[Bug]: Need to update the Zoomify version

### ISSUE THREAD

**Issue by cczzyy2020** [We-Cant-Coding/TACZ-Fabric#27]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

Minecraft 1.20.1 & Fabric Loader 0.16.7

### tac version

tacz 1.0.2-hotfix3

### Related Mods

```raw
zoomify 2.14.2+1.20.1
```

### Description

Zoomify has changed the return type of the `getZoomDivisor` function. Using the latest version of Zoomify will cause an error.
Please update the `zoomify_version` in the `gradle.properties` file (e.g. 2.14.2+1.20.1).

**Comment by LaeDev** [comment]
i will be update the zoomify version, but i cant release a new hotfix only for that. prob you need to build on your own.
