### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by edgarcnp** [We-Cant-Coding/TACZ-Fabric#4]
Will this mod eventually be uploaded to Modrinth? Obviously for easier step to download and update the mod.

Thanks for porting it to fabric anyways, really appreciate your work.

**Comment by LaeDev** [comment]
I am currently considering it. 
I'm currently looking to either end support for this mod at the end of August or find someone to take over this project, so I probably won't post it until that's done.

**Comment by RalsReal** [comment]
i found this in modrinth and it look like a reupload of this mod?

https://modrinth.com/mod/immersive-guns/changelog


![image_2024-08-03_083039788](https://github.com/user-attachments/assets/87ff0e7b-5dee-421c-8690-05b934738aa3)
![image_2024-08-03_083050743](https://github.com/user-attachments/assets/810db439-ed6d-4242-84b3-bd0a4f55f939)

this man make the same mod for the same fabric vesion?????

**Comment by RalsReal** [comment]
i am not a professional in modding but, this look like the exact same code with the change of the name


https://github.com/lukeon214/Immersive-Guns-/blob/main/src/main/java/com/imguns/guns/entity/EntityKineticBullet.java
https://github.com/We-Cant-Coding/TACZ-Fabric/blob/1.20.1/src/main/java/com/tacz/guns/entity/EntityKineticBullet.java

**Comment by LaeDev** [comment]
Under the GPL license, I can't do anything about it, but it's kind of a **dick** move not to leave a credit ( it's not mandatory, but they can leave a credit. )

**Comment by furax124** [comment]
> Under the GPL license, I can't do anything about it, but it's kind of a **dick** move not to leave a credit ( it's not mandatory, but they can leave a credit. )

They do. They mention that animation and models was from tac

**Comment by LaeDev** [comment]
> > Under the GPL license, I can't do anything about it, but it's kind of a **dick** move not to leave a credit ( it's not mandatory, but they can leave a credit. )
> 
> They do. They mention that animation and models was from tac

They mention about models. But what about my code?

**Comment by furax124** [comment]
> > > Under the GPL license, I can't do anything about it, but it's kind of a **dick** move not to leave a credit ( it's not mandatory, but they can leave a credit. )
> > 
> > They do. They mention that animation and models was from tac
> 
> They mention about models. But what about my code? They copy & pasted my code lmao 
Yeah that's is dick move lmao maybe ask him for leave a credit card?

**Comment by furax124** [comment]
> > > Under the GPL license, I can't do anything about it, but it's kind of a **dick** move not to leave a credit ( it's not mandatory, but they can leave a credit. )
> > 
> > They do. They mention that animation and models was from tac
> 
> They mention about models. But what about my code? They copy & pasted my code lmao 

Yeah that's is dick move lmao maybe ask him for leave a credit card?

**Comment by LaeDev** [comment]
> > > > Under the GPL license, I can't do anything about it, but it's kind of a **dick** move not to leave a credit ( it's not mandatory, but they can leave a credit. )
> > > 
> > > They do. They mention that animation and models was from tac
> > 
> > They mention about models. But what about my code? They copy & pasted my code lmao 
> 
> Yeah that's is dick move lmao maybe ask him for leave a credit? 

Nah. I will entirely recode my code and change the license to more strict one.

**Comment by furax124** [comment]
> > > > > Under the GPL license, I can't do anything about it, but it's kind of a **dick** move not to leave a credit ( it's not mandatory, but they can leave a credit. )
> > > > 
> > > > They do. They mention that animation and models was from tac
> > > 
> > > They mention about models. But what about my code? They copy & pasted my code lmao 
> > 
> > Yeah that's is dick move lmao maybe ask him for leave a credit? 
> 
> Nah. I will entirely recode my code and change the license to more strict one.

Yeah you don't have time to lose

**Comment by LaeDev** [comment]
Anyways. There are will be no longer updates or fixes until this resolves.

**Comment by furax124** [comment]
> Anyways. There are will be no longer updates or fixes until this resolves. 

Yeah it's normal take your time

**Comment by LaeDev** [comment]
Arranged With Original Author's Modrinth, CurseForge. Now it will upload in github, CurseForge, Modrinth.

About Immersive Guns, I will Talk with Original Author and try to take down 1.4 version and 1.4.1 version. this issue will move to separate issue.
