### ISSUE TITLE
Runing and Realoding and shooting

### ISSUE THREAD

**Issue by RalsReal** [We-Cant-Coding/TACZ-Fabric#6]
If you jump and run and spam right click some times you gonna get you weapone like something left before that you can run, shoot, and reload running, you cant see the scope some times, its kinda weird and silly, 

(Please add a config to real run and shoot, because i think it would be great)

**Comment by LaeDev** [comment]
I can't seem to reproduce the issue on my side, so if you could attach a video, that would help me fix it. Also, I'm not sure I understand what you're saying about adding the Config, so if you could elaborate a bit more, that would be helpful.

**Comment by RalsReal** [comment]
the first thing i said it's a bug, the second its a request for do it without being a bug

here the video 
https://youtu.be/9J-4QYNa4mI

**Comment by LaeDev** [comment]
The gun motion code was changed in 1.0.1, so please try it in 1.0.1 first.

**Comment by RalsReal** [comment]
It was in 1.0.1

**Comment by LaeDev** [comment]
![image](https://github.com/user-attachments/assets/d0390f7b-e5a5-4d6f-adb3-7c9e03173115)

In your demo video, it comes up as build 1.0.0.

**Comment by LaeDev** [comment]
Anyway, I'll still take a look at the internal code and fix it if I can reproduce it.

**Comment by RalsReal** [comment]
![image_2024-07-29_090558195](https://github.com/user-attachments/assets/c921a099-2758-40a3-b29c-9ac6774bd525)
huh

**Comment by LaeDev** [comment]
Weird. I'll take a break and look at the code later...

**Comment by RalsReal** [comment]
I was worng, the video was recorded in other instance(1.0), but i doesnt care because in 1.0.1 works the bug

**Comment by furax124** [comment]
> I was worng, the video was recorded in other instance(1.0), but i doesnt care because in 1.0.1 works the bug

Wtf can you be more gentle ?

**Comment by RalsReal** [comment]
huh

**Comment by RalsReal** [comment]
Oh I see, I said "I dont care", instead of saying that the version doesn't matter, English is not my first language.

**Comment by RalsReal** [comment]
sorry

**Comment by LaeDev** [comment]
same issue in forge. prob wont fix

**Comment by LaeDev** [comment]
i dont know about shit in animation so it will take some time to fix or idk
