### ISSUE TITLE
Two Akm, no rpk

### ISSUE THREAD

**Issue by RalsReal** [We-Cant-Coding/TACZ-Fabric#7]
![image_2024-07-28_142007091](https://github.com/user-attachments/assets/acac85bd-d657-4334-ac10-4a0cd80d6e9e)
![image_2024-07-28_142600063](https://github.com/user-attachments/assets/01e0d8ab-b0a5-4627-95f2-1465e0926b9a)
![image_2024-07-28_142634136](https://github.com/user-attachments/assets/b7283b68-42aa-4d29-9081-0a64878d173b)
![image_2024-07-28_142656396](https://github.com/user-attachments/assets/824d6608-4ed8-46fa-9673-ce31103dc0d4)

**Comment by LaeDev** [comment]
Same Issue in Forge, Prob Ask Community to fix or nah
