### ISSUE TITLE
If you shoot too much in f5 perpective you are going to do something weird with your head and arms

### ISSUE THREAD

**Issue by RalsReal** [We-Cant-Coding/TACZ-Fabric#8]
![image_2024-07-28_172032976](https://github.com/user-attachments/assets/b72081b6-1d4c-4916-b474-e63e757c8463)
i used perspective redux for better view

**Comment by RalsReal** [comment]
![image_2024-07-28_172232722](https://github.com/user-attachments/assets/e5f2d917-9b4a-4387-b21b-1126b5ff6e30)

**Comment by LaeDev** [comment]
Not reproducible in version 1.0.1.

**Comment by RalsReal** [comment]
Fake i didi it in 1.0.1

**Comment by LaeDev** [comment]
> Fake i didi it in 1.0.1

If you are able to reproduce this in 1.0.1, please provide more explanation or attach a demo video. Pictures are not sufficient.

**Comment by RalsReal** [comment]
https://youtu.be/UGkCpIyaEIU

**Comment by RalsReal** [comment]
Also it only works i think because perpective redux dont reset your head position

**Comment by LaeDev** [comment]
i tried to fix in 1.0.2-hotfix version. please test it and let me know about it

**Comment by RalsReal** [comment]
fixed
